export const languages = {
  en: { name: "English", locale: "en", direction: "ltr" },
  tr: { name: "Türkçe", locale: "tr", direction: "ltr" },
  ar: { name: "العربية", locale: "ar", direction: "rtl" },
  fr: { name: "Français", locale: "fr", direction: "ltr" },
  ru: { name: "Русский", locale: "ru", direction: "ltr" },
} as const;

export type LanguageCode = keyof typeof languages;

export const translations: Record<LanguageCode, Record<string, string>> = {
  en: {
    dashboard: "Dashboard",
    users: "Users",
    products: "Products",
    orders: "Orders",
    analytics: "Analytics",
    settings: "Settings",
    managementSystem: "Management System",
    administrator: "Administrator",
    profile: "Profile",
    notifications: "Notifications",
    preferences: "Preferences",
    security: "Security",
    language: "Language",
    timeZone: "Time zone",
    save: "Save changes",
    saved: "Preferences saved.",
    manageUsers: "Manage all system users",
    addUser: "Add User",
    totalUsers: "Total Users",
    activeUsers: "Active Users",
    pendingUsers: "Pending Users",
    manageOrders: "Track and manage customer orders",
    totalOrders: "Total Orders",
    openOrders: "Open Orders",
    deliveredRevenue: "Delivered Revenue",
  },
  tr: {
    dashboard: "Kontrol Paneli",
    users: "Kullanıcılar",
    products: "Ürünler",
    orders: "Siparişler",
    analytics: "Analitik",
    settings: "Ayarlar",
    managementSystem: "Yönetim Sistemi",
    administrator: "Yönetici",
    profile: "Profil",
    notifications: "Bildirimler",
    preferences: "Tercihler",
    security: "Güvenlik",
    language: "Dil",
    timeZone: "Saat dilimi",
    save: "Değişiklikleri kaydet",
    saved: "Tercihler kaydedildi.",
    manageUsers: "Tüm sistem kullanıcılarını yönetin",
    addUser: "Kullanıcı Ekle",
    totalUsers: "Toplam Kullanıcı",
    activeUsers: "Aktif Kullanıcı",
    pendingUsers: "Bekleyen Kullanıcı",
    manageOrders: "Müşteri siparişlerini takip edin ve yönetin",
    totalOrders: "Toplam Sipariş",
    openOrders: "Açık Sipariş",
    deliveredRevenue: "Teslim Edilen Gelir",
    manageProducts: "Envanterinizi yönetin",
    addProduct: "Ürün Ekle",
    inStock: "Stokta",
    inventoryValue: "Envanter Değeri",
    analyticsDescription: "Mağazanızın gelir ve müşteri performansını izleyin.",
    revenue: "Gelir",
    conversionRate: "Dönüşüm Oranı",
    averageOrderValue: "Ort. Sipariş Tutarı",
    newUser: "Yeni Kullanıcı",
    viewReports: "Raporları Görüntüle",
  },
  ar: {
    dashboard: "لوحة التحكم",
    users: "المستخدمون",
    products: "المنتجات",
    orders: "الطلبات",
    analytics: "التحليلات",
    settings: "الإعدادات",
    managementSystem: "نظام الإدارة",
    administrator: "المسؤول",
    profile: "الملف الشخصي",
    notifications: "الإشعارات",
    preferences: "التفضيلات",
    security: "الأمان",
    language: "اللغة",
    timeZone: "المنطقة الزمنية",
    save: "حفظ التغييرات",
    saved: "تم حفظ التفضيلات.",
  },
  fr: {
    dashboard: "Tableau de bord",
    users: "Utilisateurs",
    products: "Produits",
    orders: "Commandes",
    analytics: "Analyses",
    settings: "Paramètres",
    managementSystem: "Système de gestion",
    administrator: "Administrateur",
    profile: "Profil",
    notifications: "Notifications",
    preferences: "Préférences",
    security: "Sécurité",
    language: "Langue",
    timeZone: "Fuseau horaire",
    save: "Enregistrer",
    saved: "Préférences enregistrées.",
  },
  ru: {
    dashboard: "Панель управления",
    users: "Пользователи",
    products: "Товары",
    orders: "Заказы",
    analytics: "Аналитика",
    settings: "Настройки",
    managementSystem: "Система управления",
    administrator: "Администратор",
    profile: "Профиль",
    notifications: "Уведомления",
    preferences: "Настройки",
    security: "Безопасность",
    language: "Язык",
    timeZone: "Часовой пояс",
    save: "Сохранить изменения",
    saved: "Настройки сохранены.",
  },
};

Object.assign(translations.en, {
  searchUsers: "Search by name, email or role...",
  allStatuses: "All statuses",
  active: "Active",
  pending: "Pending",
  inactive: "Inactive",
  name: "Name",
  role: "Role",
  status: "Status",
  action: "Action",
  noUsers: "No users found",
  deleteUser: "Delete user",
  delete: "Delete",
  edit: "Edit",
  cancel: "Cancel",
});

Object.assign(translations.en, {
  orderStatusPending: "Pending",
  orderStatusProcessing: "Processing",
  orderStatusDelivered: "Delivered",
  orderStatusCancelled: "Cancelled",
  exportCsv: "Export CSV",
  viewOrder: "View order",
  updateOrderStatus: "Update order status",
  adjustOrderFilters: "Try changing your search or status filter.",
  orderUpdateFailed: "Unable to update order.",
  orderCreateFailed: "Unable to create order.",
  orderCreated: "created.",
});
Object.assign(translations.tr, {
  orderStatusPending: "Bekliyor",
  orderStatusProcessing: "Hazırlanıyor",
  orderStatusDelivered: "Teslim edildi",
  orderStatusCancelled: "İptal edildi",
  exportCsv: "CSV dışa aktar",
  viewOrder: "Siparişi görüntüle",
  updateOrderStatus: "Sipariş durumunu güncelle",
  adjustOrderFilters: "Aramanızı veya durum filtrenizi değiştirin.",
  orderUpdateFailed: "Sipariş güncellenemedi.",
  orderCreateFailed: "Sipariş oluşturulamadı.",
  orderCreated: "oluşturuldu.",
});
Object.assign(translations.fr, {
  orderStatusPending: "En attente",
  orderStatusProcessing: "En cours",
  orderStatusDelivered: "Livrée",
  orderStatusCancelled: "Annulée",
  exportCsv: "Exporter en CSV",
  viewOrder: "Voir la commande",
  updateOrderStatus: "Mettre à jour le statut",
  adjustOrderFilters: "Modifiez votre recherche ou votre filtre de statut.",
  orderUpdateFailed: "Impossible de mettre à jour la commande.",
  orderCreateFailed: "Impossible de créer la commande.",
  orderCreated: "créée.",
});
Object.assign(translations.ar, {
  orderStatusPending: "قيد الانتظار",
  orderStatusProcessing: "قيد المعالجة",
  orderStatusDelivered: "تم التسليم",
  orderStatusCancelled: "ملغى",
  exportCsv: "تصدير CSV",
  viewOrder: "عرض الطلب",
  updateOrderStatus: "تحديث حالة الطلب",
  adjustOrderFilters: "غيّر البحث أو فلتر الحالة.",
  orderUpdateFailed: "تعذر تحديث الطلب.",
  orderCreateFailed: "تعذر إنشاء الطلب.",
  orderCreated: "تم إنشاؤه.",
});
Object.assign(translations.ru, {
  orderStatusPending: "Ожидает",
  orderStatusProcessing: "В обработке",
  orderStatusDelivered: "Доставлен",
  orderStatusCancelled: "Отменён",
  exportCsv: "Экспорт CSV",
  viewOrder: "Просмотреть заказ",
  updateOrderStatus: "Обновить статус заказа",
  adjustOrderFilters: "Измените поиск или фильтр статуса.",
  orderUpdateFailed: "Не удалось обновить заказ.",
  orderCreateFailed: "Не удалось создать заказ.",
  orderCreated: "создан.",
});
Object.assign(translations.en, {
  editProduct: "Edit Product",
  updateProduct: "Update inventory information.",
  createProduct: "Add an item to your inventory.",
});
Object.assign(translations.tr, {
  editProduct: "Ürünü Düzenle",
  updateProduct: "Envanter bilgilerini güncelleyin.",
  createProduct: "Envanterinize yeni bir ürün ekleyin.",
});
Object.assign(translations.fr, {
  editProduct: "Modifier le produit",
  updateProduct: "Mettez à jour les informations d’inventaire.",
  createProduct: "Ajoutez un article à votre inventaire.",
});
Object.assign(translations.ru, {
  editProduct: "Изменить товар",
  updateProduct: "Обновите информацию о запасах.",
  createProduct: "Добавьте товар в инвентарь.",
});
Object.assign(translations.ar, {
  editProduct: "تعديل المنتج",
  updateProduct: "حدّث معلومات المخزون.",
  createProduct: "أضف عنصرًا إلى مخزونك.",
});
Object.assign(translations.en, {
  recentOrders: "Recent Orders",
  searchOrders: "Search order or customer...",
  noOrders: "No orders found",
});
Object.assign(translations.tr, {
  recentOrders: "Son Siparişler",
  searchOrders: "Sipariş veya müşteri ara...",
  noOrders: "Sipariş bulunamadı",
});
Object.assign(translations.fr, {
  recentOrders: "Commandes récentes",
  searchOrders: "Rechercher une commande ou un client...",
  noOrders: "Aucune commande trouvée",
});
Object.assign(translations.ru, {
  recentOrders: "Последние заказы",
  searchOrders: "Поиск заказа или клиента...",
  noOrders: "Заказы не найдены",
});
Object.assign(translations.ar, {
  recentOrders: "الطلبات الأخيرة",
  searchOrders: "ابحث عن طلب أو عميل...",
  noOrders: "لم يتم العثور على طلبات",
});
Object.assign(translations.en, {
  salesOverview: "Sales Overview",
  monthlySales: "Monthly sales performance",
  currentMonth: "Current month",
  totalRevenue: "Total Revenue",
});
Object.assign(translations.tr, {
  salesOverview: "Satış Özeti",
  monthlySales: "Aylık satış performansı",
  currentMonth: "Bu ay",
  totalRevenue: "Toplam Gelir",
});
Object.assign(translations.fr, {
  salesOverview: "Aperçu des ventes",
  monthlySales: "Performances mensuelles des ventes",
  currentMonth: "Mois en cours",
  totalRevenue: "Revenus totaux",
});
Object.assign(translations.ru, {
  salesOverview: "Обзор продаж",
  monthlySales: "Ежемесячные показатели продаж",
  currentMonth: "Текущий месяц",
  totalRevenue: "Общий доход",
});
Object.assign(translations.ar, {
  salesOverview: "نظرة عامة على المبيعات",
  monthlySales: "أداء المبيعات الشهري",
  currentMonth: "الشهر الحالي",
  totalRevenue: "إجمالي الإيرادات",
});
Object.assign(translations.en, {
  emailNotifications: "Email notifications",
  orderActivity: "Order activity",
  weeklyReports: "Weekly reports",
});
Object.assign(translations.tr, {
  emailNotifications: "E-posta bildirimleri",
  orderActivity: "Sipariş hareketleri",
  weeklyReports: "Haftalık raporlar",
});
Object.assign(translations.fr, {
  emailNotifications: "Notifications par e-mail",
  orderActivity: "Activité des commandes",
  weeklyReports: "Rapports hebdomadaires",
});
Object.assign(translations.ru, {
  emailNotifications: "Уведомления по электронной почте",
  orderActivity: "Активность заказов",
  weeklyReports: "Еженедельные отчёты",
});
Object.assign(translations.ar, {
  emailNotifications: "إشعارات البريد الإلكتروني",
  orderActivity: "نشاط الطلبات",
  weeklyReports: "التقارير الأسبوعية",
});
Object.assign(translations.en, {
  unreadUpdates: "unread updates",
  markAllRead: "Mark all read",
  notificationOrderTitle: "New order received",
  notificationOrderDescription: "Order #1048 was placed a few minutes ago.",
  notificationOrderTime: "5m ago",
  notificationStockTitle: "Low stock alert",
  notificationStockDescription: "Apple Watch Ultra has only 7 items left.",
  notificationStockTime: "1h ago",
  notificationReportTitle: "Weekly report ready",
  notificationReportDescription: "Your performance report is ready to view.",
  notificationReportTime: "3h ago",
});
Object.assign(translations.tr, {
  unreadUpdates: "okunmamış güncelleme",
  markAllRead: "Tümünü okundu işaretle",
  notificationOrderTitle: "Yeni sipariş alındı",
  notificationOrderDescription:
    "#1048 numaralı sipariş birkaç dakika önce oluşturuldu.",
  notificationOrderTime: "5 dk önce",
  notificationStockTitle: "Düşük stok uyarısı",
  notificationStockDescription: "Apple Watch Ultra için yalnızca 7 ürün kaldı.",
  notificationStockTime: "1 sa önce",
  notificationReportTitle: "Haftalık rapor hazır",
  notificationReportDescription: "Performans raporunuz görüntülemeye hazır.",
  notificationReportTime: "3 sa önce",
});
Object.assign(translations.fr, {
  unreadUpdates: "mises à jour non lues",
  markAllRead: "Tout marquer comme lu",
  notificationOrderTitle: "Nouvelle commande reçue",
  notificationOrderDescription: "La commande #1048 vient d’être passée.",
  notificationOrderTime: "il y a 5 min",
  notificationStockTitle: "Alerte de stock faible",
  notificationStockDescription: "Il ne reste que 7 Apple Watch Ultra.",
  notificationStockTime: "il y a 1 h",
  notificationReportTitle: "Rapport hebdomadaire prêt",
  notificationReportDescription: "Votre rapport de performance est prêt.",
  notificationReportTime: "il y a 3 h",
});
Object.assign(translations.ru, {
  unreadUpdates: "непрочитанных обновлений",
  markAllRead: "Прочитать все",
  notificationOrderTitle: "Получен новый заказ",
  notificationOrderDescription:
    "Заказ #1048 был оформлен несколько минут назад.",
  notificationOrderTime: "5 мин назад",
  notificationStockTitle: "Предупреждение о низком запасе",
  notificationStockDescription: "Осталось только 7 Apple Watch Ultra.",
  notificationStockTime: "1 ч назад",
  notificationReportTitle: "Еженедельный отчёт готов",
  notificationReportDescription: "Ваш отчёт о производительности готов.",
  notificationReportTime: "3 ч назад",
});
Object.assign(translations.ar, {
  unreadUpdates: "تحديثات غير مقروءة",
  markAllRead: "وضع علامة الكل كمقروء",
  notificationOrderTitle: "تم استلام طلب جديد",
  notificationOrderDescription: "تم إنشاء الطلب #1048 قبل بضع دقائق.",
  notificationOrderTime: "منذ 5 دقائق",
  notificationStockTitle: "تنبيه مخزون منخفض",
  notificationStockDescription: "تبقى 7 قطع فقط من Apple Watch Ultra.",
  notificationStockTime: "منذ ساعة",
  notificationReportTitle: "التقرير الأسبوعي جاهز",
  notificationReportDescription: "تقرير الأداء الخاص بك جاهز للعرض.",
  notificationReportTime: "منذ 3 ساعات",
});
Object.assign(translations.en, {
  revenueComparison: "18% compared to last month",
});
Object.assign(translations.tr, {
  revenueComparison: "geçen aya göre %18 artış",
});
Object.assign(translations.fr, {
  revenueComparison: "18 % de plus que le mois dernier",
});
Object.assign(translations.ru, {
  revenueComparison: "на 18 % больше, чем в прошлом месяце",
});
Object.assign(translations.ar, {
  revenueComparison: "زيادة 18٪ مقارنة بالشهر الماضي",
});
Object.assign(translations.en, { thisMonth: "this month" });
Object.assign(translations.tr, { thisMonth: "bu ay" });
Object.assign(translations.fr, { thisMonth: "ce mois-ci" });
Object.assign(translations.ru, { thisMonth: "в этом месяце" });
Object.assign(translations.ar, { thisMonth: "هذا الشهر" });
Object.assign(translations.tr, {
  searchUsers: "Ad, e-posta veya role göre ara...",
  allStatuses: "Tüm durumlar",
  active: "Aktif",
  pending: "Bekliyor",
  inactive: "Pasif",
  name: "Ad",
  role: "Rol",
  status: "Durum",
  action: "İşlem",
  noUsers: "Kullanıcı bulunamadı",
  deleteUser: "Kullanıcıyı sil",
  delete: "Sil",
  edit: "Düzenle",
  cancel: "İptal",
});
Object.assign(translations.en, {
  searchProducts: "Search product...",
  allCategories: "All categories",
  stock: "Stock",
  product: "Product",
  category: "Category",
  price: "Price",
  noProducts: "No products found",
  deleteProduct: "Delete product",
});
Object.assign(translations.tr, {
  searchProducts: "Ürün ara...",
  allCategories: "Tüm kategoriler",
  stock: "Stok",
  product: "Ürün",
  category: "Kategori",
  price: "Fiyat",
  noProducts: "Ürün bulunamadı",
  deleteProduct: "Ürünü sil",
});
Object.assign(translations.en, {
  createUser: "Create a new dashboard user.",
  fullName: "Full Name",
  email: "Email",
  saveUser: "Save User",
});
Object.assign(translations.tr, {
  createUser: "Yeni bir panel kullanıcısı oluşturun.",
  fullName: "Ad soyad",
  email: "E-posta",
  saveUser: "Kullanıcıyı Kaydet",
});
Object.assign(translations.en, {
  editUser: "Edit User",
  updateUser: "Update this user's information.",
});
Object.assign(translations.tr, {
  editUser: "Kullanıcıyı Düzenle",
  updateUser: "Bu kullanıcının bilgilerini güncelleyin.",
});
Object.assign(translations.fr, {
  manageUsers: "Gérez tous les utilisateurs du système",
  addUser: "Ajouter un utilisateur",
  totalUsers: "Utilisateurs totaux",
  activeUsers: "Utilisateurs actifs",
  pendingUsers: "Utilisateurs en attente",
  manageOrders: "Suivez et gérez les commandes clients",
  totalOrders: "Commandes totales",
  openOrders: "Commandes ouvertes",
  deliveredRevenue: "Revenus livrés",
  manageProducts: "Gérez votre inventaire",
  addProduct: "Ajouter un produit",
  inStock: "En stock",
  inventoryValue: "Valeur du stock",
  analyticsDescription: "Suivez les revenus et les performances clients.",
  revenue: "Revenus",
  conversionRate: "Taux de conversion",
  averageOrderValue: "Panier moyen",
  newUser: "Nouvel utilisateur",
  viewReports: "Voir les rapports",
  searchUsers: "Rechercher par nom, e-mail ou rôle...",
  allStatuses: "Tous les statuts",
  active: "Actif",
  pending: "En attente",
  inactive: "Inactif",
  name: "Nom",
  role: "Rôle",
  status: "Statut",
  action: "Action",
  noUsers: "Aucun utilisateur trouvé",
  deleteUser: "Supprimer l’utilisateur",
  delete: "Supprimer",
  edit: "Modifier",
  cancel: "Annuler",
  createUser: "Créez un nouvel utilisateur du tableau de bord.",
  fullName: "Nom complet",
  email: "E-mail",
  saveUser: "Enregistrer l’utilisateur",
  editUser: "Modifier l’utilisateur",
  updateUser: "Mettez à jour les informations de cet utilisateur.",
});
Object.assign(translations.ru, {
  manageUsers: "Управляйте всеми пользователями системы",
  addUser: "Добавить пользователя",
  totalUsers: "Всего пользователей",
  activeUsers: "Активные пользователи",
  pendingUsers: "Ожидающие пользователи",
  manageOrders: "Отслеживайте и управляйте заказами клиентов",
  totalOrders: "Всего заказов",
  openOrders: "Открытые заказы",
  deliveredRevenue: "Доход от доставок",
  manageProducts: "Управляйте своим инвентарём",
  addProduct: "Добавить товар",
  inStock: "В наличии",
  inventoryValue: "Стоимость запасов",
  analyticsDescription: "Отслеживайте доход и показатели клиентов.",
  revenue: "Доход",
  conversionRate: "Коэффициент конверсии",
  averageOrderValue: "Средний чек",
  newUser: "Новый пользователь",
  viewReports: "Смотреть отчёты",
  searchUsers: "Поиск по имени, e-mail или роли...",
  allStatuses: "Все статусы",
  active: "Активный",
  pending: "Ожидает",
  inactive: "Неактивный",
  name: "Имя",
  role: "Роль",
  status: "Статус",
  action: "Действие",
  noUsers: "Пользователи не найдены",
  deleteUser: "Удалить пользователя",
  delete: "Удалить",
  edit: "Изменить",
  cancel: "Отмена",
  createUser: "Создайте нового пользователя панели.",
  fullName: "Полное имя",
  email: "Эл. почта",
  saveUser: "Сохранить пользователя",
  editUser: "Изменить пользователя",
  updateUser: "Обновите данные этого пользователя.",
});
Object.assign(translations.ar, {
  manageUsers: "إدارة جميع مستخدمي النظام",
  addUser: "إضافة مستخدم",
  totalUsers: "إجمالي المستخدمين",
  activeUsers: "المستخدمون النشطون",
  pendingUsers: "المستخدمون قيد الانتظار",
  manageOrders: "تتبع وإدارة طلبات العملاء",
  totalOrders: "إجمالي الطلبات",
  openOrders: "الطلبات المفتوحة",
  deliveredRevenue: "إيرادات الطلبات المسلّمة",
  manageProducts: "إدارة مخزونك",
  addProduct: "إضافة منتج",
  inStock: "متوفر في المخزون",
  inventoryValue: "قيمة المخزون",
  analyticsDescription: "راقب إيرادات متجرك وأداء العملاء.",
  revenue: "الإيرادات",
  conversionRate: "معدل التحويل",
  averageOrderValue: "متوسط قيمة الطلب",
  newUser: "مستخدم جديد",
  viewReports: "عرض التقارير",
  searchUsers: "البحث بالاسم أو البريد أو الدور...",
  allStatuses: "كل الحالات",
  active: "نشط",
  pending: "قيد الانتظار",
  inactive: "غير نشط",
  name: "الاسم",
  role: "الدور",
  status: "الحالة",
  action: "إجراء",
  noUsers: "لم يتم العثور على مستخدمين",
  deleteUser: "حذف المستخدم",
  delete: "حذف",
  edit: "تعديل",
  cancel: "إلغاء",
  createUser: "أنشئ مستخدم لوحة تحكم جديدًا.",
  fullName: "الاسم الكامل",
  email: "البريد الإلكتروني",
  saveUser: "حفظ المستخدم",
  editUser: "تعديل المستخدم",
  updateUser: "حدّث معلومات هذا المستخدم.",
});
Object.assign(translations.en, {
  addOrder: "Add Order",
  addOrderDescription: "Create a new customer order.",
  orderDetails: "Order details",
  order: "Order",
  customerName: "Customer name",
  items: "Items",
  total: "Total",
  date: "Date",
  processing: "Processing",
  delivered: "Delivered",
  cancelled: "Cancelled",
  close: "Close",
  saving: "Saving...",
});
Object.assign(translations.tr, {
  addOrder: "Sipariş Ekle",
  addOrderDescription: "Yeni bir müşteri siparişi oluşturun.",
  orderDetails: "Sipariş detayları",
  order: "Sipariş",
  customerName: "Müşteri adı",
  items: "Ürün adedi",
  total: "Toplam",
  date: "Tarih",
  processing: "Hazırlanıyor",
  delivered: "Teslim edildi",
  cancelled: "İptal edildi",
  close: "Kapat",
  saving: "Kaydediliyor...",
});
Object.assign(translations.fr, {
  addOrder: "Ajouter une commande",
  addOrderDescription: "Créez une nouvelle commande client.",
  orderDetails: "Détails de la commande",
  order: "Commande",
  customerName: "Nom du client",
  items: "Articles",
  total: "Total",
  date: "Date",
  processing: "En cours",
  delivered: "Livrée",
  cancelled: "Annulée",
  close: "Fermer",
  saving: "Enregistrement...",
});
Object.assign(translations.ar, {
  addOrder: "إضافة طلب",
  addOrderDescription: "أنشئ طلب عميل جديد.",
  orderDetails: "تفاصيل الطلب",
  order: "الطلب",
  customerName: "اسم العميل",
  items: "العناصر",
  total: "الإجمالي",
  date: "التاريخ",
  processing: "قيد المعالجة",
  delivered: "تم التسليم",
  cancelled: "ملغى",
  close: "إغلاق",
  saving: "جارٍ الحفظ...",
});
Object.assign(translations.ru, {
  addOrder: "Добавить заказ",
  addOrderDescription: "Создайте новый заказ клиента.",
  orderDetails: "Детали заказа",
  order: "Заказ",
  customerName: "Имя клиента",
  items: "Товары",
  total: "Итого",
  date: "Дата",
  processing: "В обработке",
  delivered: "Доставлен",
  cancelled: "Отменён",
  close: "Закрыть",
  saving: "Сохранение...",
});
