export const languages = {
  en: { name: "English", locale: "en", direction: "ltr" },
  tr: { name: "Türkçe", locale: "tr", direction: "ltr" },
  ar: { name: "العربية", locale: "ar", direction: "rtl" },
  fr: { name: "Français", locale: "fr", direction: "ltr" },
  ru: { name: "Русский", locale: "ru", direction: "ltr" },
} as const;

export type LanguageCode = keyof typeof languages;

export const translations: Record<LanguageCode, Record<string, string>> = {
  en: { dashboard: "Dashboard", users: "Users", products: "Products", orders: "Orders", analytics: "Analytics", settings: "Settings", managementSystem: "Management System", administrator: "Administrator", profile: "Profile", notifications: "Notifications", preferences: "Preferences", security: "Security", language: "Language", timeZone: "Time zone", save: "Save changes", saved: "Preferences saved.", manageUsers: "Manage all system users", addUser: "Add User", totalUsers: "Total Users", activeUsers: "Active Users", pendingUsers: "Pending Users", manageOrders: "Track and manage customer orders", totalOrders: "Total Orders", openOrders: "Open Orders", deliveredRevenue: "Delivered Revenue" },
  tr: { dashboard: "Kontrol Paneli", users: "Kullanıcılar", products: "Ürünler", orders: "Siparişler", analytics: "Analitik", settings: "Ayarlar", managementSystem: "Yönetim Sistemi", administrator: "Yönetici", profile: "Profil", notifications: "Bildirimler", preferences: "Tercihler", security: "Güvenlik", language: "Dil", timeZone: "Saat dilimi", save: "Değişiklikleri kaydet", saved: "Tercihler kaydedildi.", manageUsers: "Tüm sistem kullanıcılarını yönetin", addUser: "Kullanıcı Ekle", totalUsers: "Toplam Kullanıcı", activeUsers: "Aktif Kullanıcı", pendingUsers: "Bekleyen Kullanıcı", manageOrders: "Müşteri siparişlerini takip edin ve yönetin", totalOrders: "Toplam Sipariş", openOrders: "Açık Sipariş", deliveredRevenue: "Teslim Edilen Gelir", manageProducts: "Envanterinizi yönetin", addProduct: "Ürün Ekle", inStock: "Stokta", inventoryValue: "Envanter Değeri", analyticsDescription: "Mağazanızın gelir ve müşteri performansını izleyin.", revenue: "Gelir", conversionRate: "Dönüşüm Oranı", averageOrderValue: "Ort. Sipariş Tutarı", newUser: "Yeni Kullanıcı", viewReports: "Raporları Görüntüle" },
  ar: { dashboard: "لوحة التحكم", users: "المستخدمون", products: "المنتجات", orders: "الطلبات", analytics: "التحليلات", settings: "الإعدادات", managementSystem: "نظام الإدارة", administrator: "المسؤول", profile: "الملف الشخصي", notifications: "الإشعارات", preferences: "التفضيلات", security: "الأمان", language: "اللغة", timeZone: "المنطقة الزمنية", save: "حفظ التغييرات", saved: "تم حفظ التفضيلات." },
  fr: { dashboard: "Tableau de bord", users: "Utilisateurs", products: "Produits", orders: "Commandes", analytics: "Analyses", settings: "Paramètres", managementSystem: "Système de gestion", administrator: "Administrateur", profile: "Profil", notifications: "Notifications", preferences: "Préférences", security: "Sécurité", language: "Langue", timeZone: "Fuseau horaire", save: "Enregistrer", saved: "Préférences enregistrées." },
  ru: { dashboard: "Панель управления", users: "Пользователи", products: "Товары", orders: "Заказы", analytics: "Аналитика", settings: "Настройки", managementSystem: "Система управления", administrator: "Администратор", profile: "Профиль", notifications: "Уведомления", preferences: "Настройки", security: "Безопасность", language: "Язык", timeZone: "Часовой пояс", save: "Сохранить изменения", saved: "Настройки сохранены." },
};

Object.assign(translations.en, { searchUsers: "Search by name, email or role...", allStatuses: "All statuses", active: "Active", pending: "Pending", inactive: "Inactive", name: "Name", role: "Role", status: "Status", action: "Action", noUsers: "No users found", deleteUser: "Delete user", delete: "Delete", edit: "Edit", cancel: "Cancel" });
Object.assign(translations.tr, { searchUsers: "Ad, e-posta veya role göre ara...", allStatuses: "Tüm durumlar", active: "Aktif", pending: "Bekliyor", inactive: "Pasif", name: "Ad", role: "Rol", status: "Durum", action: "İşlem", noUsers: "Kullanıcı bulunamadı", deleteUser: "Kullanıcıyı sil", delete: "Sil", edit: "Düzenle", cancel: "İptal" });
Object.assign(translations.en, { searchProducts: "Search product...", allCategories: "All categories", stock: "Stock", product: "Product", category: "Category", price: "Price", noProducts: "No products found", deleteProduct: "Delete product" });
Object.assign(translations.tr, { searchProducts: "Ürün ara...", allCategories: "Tüm kategoriler", stock: "Stok", product: "Ürün", category: "Kategori", price: "Fiyat", noProducts: "Ürün bulunamadı", deleteProduct: "Ürünü sil" });
Object.assign(translations.en, { createUser: "Create a new dashboard user.", fullName: "Full Name", email: "Email", saveUser: "Save User" });
Object.assign(translations.tr, { createUser: "Yeni bir panel kullanıcısı oluşturun.", fullName: "Ad soyad", email: "E-posta", saveUser: "Kullanıcıyı Kaydet" });
Object.assign(translations.en, { editUser: "Edit User", updateUser: "Update this user's information." });
Object.assign(translations.tr, { editUser: "Kullanıcıyı Düzenle", updateUser: "Bu kullanıcının bilgilerini güncelleyin." });
Object.assign(translations.fr, { manageUsers: "Gérez tous les utilisateurs du système", addUser: "Ajouter un utilisateur", totalUsers: "Utilisateurs totaux", activeUsers: "Utilisateurs actifs", pendingUsers: "Utilisateurs en attente", manageOrders: "Suivez et gérez les commandes clients", totalOrders: "Commandes totales", openOrders: "Commandes ouvertes", deliveredRevenue: "Revenus livrés", manageProducts: "Gérez votre inventaire", addProduct: "Ajouter un produit", inStock: "En stock", inventoryValue: "Valeur du stock", analyticsDescription: "Suivez les revenus et les performances clients.", revenue: "Revenus", conversionRate: "Taux de conversion", averageOrderValue: "Panier moyen", newUser: "Nouvel utilisateur", viewReports: "Voir les rapports", searchUsers: "Rechercher par nom, e-mail ou rôle...", allStatuses: "Tous les statuts", active: "Actif", pending: "En attente", inactive: "Inactif", name: "Nom", role: "Rôle", status: "Statut", action: "Action", noUsers: "Aucun utilisateur trouvé", deleteUser: "Supprimer l’utilisateur", delete: "Supprimer", edit: "Modifier", cancel: "Annuler", createUser: "Créez un nouvel utilisateur du tableau de bord.", fullName: "Nom complet", email: "E-mail", saveUser: "Enregistrer l’utilisateur", editUser: "Modifier l’utilisateur", updateUser: "Mettez à jour les informations de cet utilisateur." });
Object.assign(translations.ru, { manageUsers: "Управляйте всеми пользователями системы", addUser: "Добавить пользователя", totalUsers: "Всего пользователей", activeUsers: "Активные пользователи", pendingUsers: "Ожидающие пользователи", manageOrders: "Отслеживайте и управляйте заказами клиентов", totalOrders: "Всего заказов", openOrders: "Открытые заказы", deliveredRevenue: "Доход от доставок", manageProducts: "Управляйте своим инвентарём", addProduct: "Добавить товар", inStock: "В наличии", inventoryValue: "Стоимость запасов", analyticsDescription: "Отслеживайте доход и показатели клиентов.", revenue: "Доход", conversionRate: "Коэффициент конверсии", averageOrderValue: "Средний чек", newUser: "Новый пользователь", viewReports: "Смотреть отчёты", searchUsers: "Поиск по имени, e-mail или роли...", allStatuses: "Все статусы", active: "Активный", pending: "Ожидает", inactive: "Неактивный", name: "Имя", role: "Роль", status: "Статус", action: "Действие", noUsers: "Пользователи не найдены", deleteUser: "Удалить пользователя", delete: "Удалить", edit: "Изменить", cancel: "Отмена", createUser: "Создайте нового пользователя панели.", fullName: "Полное имя", email: "Эл. почта", saveUser: "Сохранить пользователя", editUser: "Изменить пользователя", updateUser: "Обновите данные этого пользователя." });
Object.assign(translations.ar, { manageUsers: "إدارة جميع مستخدمي النظام", addUser: "إضافة مستخدم", totalUsers: "إجمالي المستخدمين", activeUsers: "المستخدمون النشطون", pendingUsers: "المستخدمون قيد الانتظار", manageOrders: "تتبع وإدارة طلبات العملاء", totalOrders: "إجمالي الطلبات", openOrders: "الطلبات المفتوحة", deliveredRevenue: "إيرادات الطلبات المسلّمة", manageProducts: "إدارة مخزونك", addProduct: "إضافة منتج", inStock: "متوفر في المخزون", inventoryValue: "قيمة المخزون", analyticsDescription: "راقب إيرادات متجرك وأداء العملاء.", revenue: "الإيرادات", conversionRate: "معدل التحويل", averageOrderValue: "متوسط قيمة الطلب", newUser: "مستخدم جديد", viewReports: "عرض التقارير", searchUsers: "البحث بالاسم أو البريد أو الدور...", allStatuses: "كل الحالات", active: "نشط", pending: "قيد الانتظار", inactive: "غير نشط", name: "الاسم", role: "الدور", status: "الحالة", action: "إجراء", noUsers: "لم يتم العثور على مستخدمين", deleteUser: "حذف المستخدم", delete: "حذف", edit: "تعديل", cancel: "إلغاء", createUser: "أنشئ مستخدم لوحة تحكم جديدًا.", fullName: "الاسم الكامل", email: "البريد الإلكتروني", saveUser: "حفظ المستخدم", editUser: "تعديل المستخدم", updateUser: "حدّث معلومات هذا المستخدم." });
